version: 0.0

os: linux

files:
  - source: smartaddress-web-1.0-SNAPSHOT.jar
    destination: /tmp

hooks:
  ApplicationStop:
    - location: stop-server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: create_or_update_service.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start-server.sh
      timeout: 300
      runas: ec2-user    