version: 0.0

os: linux

files:
  - source: smartaddress-web-1.0-SNAPSHOT.jar
    destination: /tmp

hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/create_or_update_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 300
      runas: root    