version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
    - location: create_or_update_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: fix_previleges.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start-server.sh
      timeout: 300
      runas: root    
  ApplicationStop:
    - location: stop-server.sh
      timeout: 300
      runas: root
      