version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t smartaddress:latest .
      - docker tag smartaddress:latest 151776671846.dkr.ecr.ap-southeast-2.amazonaws.com/smartaddress:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 151776671846.dkr.ecr.ap-southeast-2.amazonaws.com/smartaddress:latest