logging:
  group:
    api: com.smartapps.smartaddress.web
  level:
    api: trace
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        boot:
          autoconfigure: ERROR
spring:
  application:
    name: SmartAddress API
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:smartdb
    username: sa
    password: ''
    driverClassNamee: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    display-query-params-without-oauth2: true
    displayRequestDuration: true
    tagsSorter: alpha
  version: '@project.version@'
