DROP ALL OBJECTS;

CREATE TABLE SMART_ADDRESS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT,
  ADDRESS_LINE1 VARCHAR(100),
  ADDRESS_LINE2 VARCHAR(100),
  CITY VARCHAR(100),
  STATE VARCHAR(100),
  COUNTRY VARCHAR(100),
  POSTAL_CODE VARCHAR(100),
  LATITUDE VARCHAR(100),
  LONGITUDE VARCHAR(100),
  START_DATE DATE,
  END_DATE DATE,
  PROC_TS TIMESTAMP,
  PROC_APP_ID VARCHAR(50),
  PROC_USER_ID VARCHAR(50),
  PROC_USER_IP_ADDRESS VARCHAR(50),
  PROC_USER_LATITUDE VARCHAR(100),
  PROC_USER_LONGITUDE VARCHAR(100),
  VERS_ID smallint NOT NULL
);
